### ISSUE TITLE
image pruning

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#102]
Pruning images needs a little work.

* remove dependency on a local catalog of images - use `refresh-releases` code to get an in-memory assessment of what images are currently out there
* default for `prune-amis` (`prune-images`?) is to report what _would_ be done.  An additional flag must be provided to _really_ do the pruning.
* don't report unknown images by default -- but the ability to do so is useful (finding images that weren't tagged properly)
* `refresh-releases` afterward to keep `releases/<profile>.yaml` updated with reality

**Comment by tomalok** [comment]
Working on a bigger shake-up than intended...  including a new `Releases` class for release-data based operations...
* get data for all the existing released images
* reorganize into a 'releases' data structure
* output releases YAML (currently to a file, but export to an S3/object storage bucket, or in JSON format instead is doable)
* figure out which releases are ready to be pruned.

Regarding that last item, I'm reviewing the old logic -- before we built for different architectures.  That's going to require some changes because build_time is going to be different between `x86_64` and `aarch64`, and will need to be tracked separately.  While I'm at it, going to puzzle through the rest of it and see if we may need to do something about builds in the same profile that _don't_ differ by version/arch...  (i.e. `alpine-ami-minimal` vs `alpine-ami-cloudinit`)...

**Comment by tomalok** [comment]
Nearly done with this (just needed to update the README builder) -- and then realized that the different archs are in separate profile builds, and ***that's*** what needs to be tracked.

@mcrute: I've been building/releasing **edge** AMIs to validate the code changes -- I haven't yet wired in the actual AMI deletion yet (just showing what _would_ be pruned), but that will likely happen soon -- I'll be limiting my `prune` testing to **edge**, and making sure that the current edge listed in **releases/README.md** remains in place, at least until that's updated with the latest edge.

Also, new `prune` features...
* `version` level has been renamed `end-of-life`
* `UNKNOWN` level prunes AMIs that do not have a `profile` tag...  (the actual profile positional parameter is ignored in this case)
* `--keep <N>` keeps the latest _N_ additional images that would have been pruned otherwise
* `--delay-eol <DAYS>` extends the time before EOL'd images are selected for pruning
* `--no-pretend` is the trigger for _actually_ doing the image deletion.

**Comment by mcrute** [comment]
Sounds good! Did you hack around with data backfill for older AMIs or should I grab that task? I'll have some time over the next 5 days to hack on stuff, finally.

**Comment by tomalok** [comment]
Nope, didn't touch the data backfill -- but a `prune UNKNOWN` now does a good job of listing everything that's missing a `profile` tag, at least...  ;)
