### ISSUE TITLE
==> amazon-ebssurrogate: ERROR: Newer Alpine release detected: 3.13.1

### ISSUE THREAD

**Issue by zfLQ2qx2** [mcrute/alpine-ec2-ami#110]
I'm trying have our ci/cd build the latest Alpine image - I'm using version/current in the profile definition, but I encountered this error while building:

==> amazon-ebssurrogate: ERROR: Newer Alpine release detected: 3.13.1

Is there a way that I can tell the builder script to build the latest release, or the latest release it knows about, even if there is a newer one? I know that at some point everything will update and a future build will get the latest release.

**Comment by tomalok** [comment]
It looks like a new release landed yesterday.  I'll get that updated now.

if you don't want to wait for the PR to be merged, you can update `release` in **profiles/version/3.13**

**Comment by zfLQ2qx2** [comment]
@tomalok The quesition is more about automation - is there a way to have this just build the latest release it knows about - i.e. existence of a newer build should not kill the build.
