### ISSUE TITLE
==> amazon-ebssurrogate: ERROR: Newer Alpine release detected: 3.13.1

### ISSUE THREAD

**Issue by zfLQ2qx2** [mcrute/alpine-ec2-ami#112]
@tomalok This is a follow-up to #110 which was closed. The question was more about automation, is there a way to have the builder script just build the latest release it knows of? i.e. existence of a newer release shouldn't kill the build. If I'm building AMIs as part of a CI/CD pipeline I don't want all the pipelines to die while waiting for someone to merge a fix to this repo.

**Comment by tomalok** [comment]
This has been a long-term "To-Do" item that's been at the bottom of https://github.com/mcrute/alpine-ec2-ami/blob/master/README.md under *Caveats* for quite a long time.

The big reason it hasn't been addressed previously is that by the time we had the Alpine release available to us, we were already inside the build, and not able to get that information outside the instance that was launched for the build and make that simple update.

I'm currently contemplating some level of rewrite to expand this from just AWS AMIs to also build images for other cloud providers, and solving this particular annoyance is in the mix.  I gave it a couple moments of thought this past weekend, and it should be doable -- but I don't know offhand how difficult it'd be able to add to the current build process.  Certainly, when we're dealing with 4 non-EOL Alpine versions (plus edge) times *N* cloud providers (some that support multiple image architectures), times however many feature sets we have (i.e. cloud-init, and minimal)...  You can see how solving this would probably be a good thing as we work towards integrating this into Alpine Linux's CI/CD, too.

Out of curiosity, what CI/CD pipeline have you been working with, and how's that been working for you (apart from this particular issue)?

**Comment by zfLQ2qx2** [comment]
@tomalok I'm using AWS CodePipeline to launch a CodeBuild process which runs packer to build the Alpine AMI then uses CodeDeploy to update a cloudformation template with the new AMI Id. From there some additional configuration is done on instance boot in start up scripts. I'm not too excited about the last part, its on my to-do to see if I can find a place I can inject a custom configuration script to run on the packer builder. Overall though the alpine-ec2-ami part seems to just work aside form the new release issue, it spits out an ami Id in only a couple minutes, hard to beat that. Its much more AWS friendly then CentOS ever was and no systemd to fuss with.

**Comment by zfLQ2qx2** [comment]
I see where to inject a script - https://github.com/mcrute/alpine-ec2-ami/blob/master/profiles/test.conf#L18

**Comment by tomalok** [comment]
Yep, I added that feature a couple cycles ago, I use it for fleshing out my custom images.  If the setup script needs additional artifacts (or needs to call other scripts), you can define them with `setup_copy` -- there's a little bit of documentation hidden towards the bottom of https://github.com/mcrute/alpine-ec2-ami/tree/master/profiles/README.md, starting with "Further customization..."

I managed to hack together a way to determine a version's release before building it -- I'll create the PR later today.

**Comment by zfLQ2qx2** [comment]
@tomalok Awesome! I'll give it a shot as soon as I see it
