### ISSUE TITLE
setup_copy

### ISSUE THREAD

**Issue by zfLQ2qx2** [mcrute/alpine-ec2-ami#114]
I've got a setup script defined in my profile and working, but I'm running into problems with setup_copy. I've created a directory alpine-ec2-ami/local with content I want to place into the image via my setup script. I've been doing trial and error with various values to setup_copy to get that directory placed into /tmp/setup-ami.d/local and I'm not seeing errors, but when I run a "find" from my setup script the files don't show up anyplace under /tmp/setup-ami.d.

**Comment by tomalok** [comment]
How are you setting the `setup_copy` map?  If I remember correctly, the keys are tdestinations _under_ /tmp/setup-ami.d (on the build instance, not the target directory that eventually becomes the new image), and the value is the path (relative or absolute) to the local file/directory to copy.

For example, here's what I'm using for my custom image...
```
  setup_script = ../jn-ec2-ami/jn-setup.sh
  setup_copy = {
    setup = ../jn-ec2-ami/setup
}
```
The paths to the script and directory to copy are relative to the top directory of the alpine-ec2-ami directory, and they should both end up in /tmp/setup-ami.d...  Also, when the extra setup script runs, its working directory also is /tmp/setup-ami.d.

The environment variable TARGET is also passed to the setup script for a shortcut to the `setup_script` so you can do stuff like...
```
cp -a ./setup "$TARGET/setup"
chroot "$TARGET" /setup/preload-bootstrap.sh
chroot "$TARGET" /setup/config-docker.sh
# etc.
ls -alF "$TARGET"
ls -alF .
echo "$PWD"
```

**Comment by zfLQ2qx2** [comment]
@tomalok Based on your example I created the subdirectory alpine-ec2-ami/local with a number of files in it and then did this:

```
    setup_copy {
      local = ./local
    }
```
And it worked! :balloon::tropical_drink::tada::cake::balloon: Thank you so much, this is twice this week you've aided me, much appreciated! I think I'll be able to find my own way from here.
