### ISSUE TITLE
Updates...

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#12]
Alpinelinux edge now has a `linux-virt` that supports NVMe, a `ec2-eni-driver-virt`, and an updated `tiny-ec2-bootstrap`.

And, as @mcrute has suggested, `variables.json*` would probably be better off as yaml, converted just prior to the Packer build.

I'll likely start poking at these soon.

**Comment by tomalok** [comment]
Submitted PR #13.

**Comment by mcrute** [comment]
PR #13 is merged. Closing this issue.
