### ISSUE TITLE
EC2 aarch64 3.13.5 won't boot after upgrade. 

### ISSUE THREAD

**Issue by Entelin** [mcrute/alpine-ec2-ami#121]
To reproduce: Create an ec2 instance from the website: (aarch64, 3.13.5)
https://us-east-1.console.aws.amazon.com/ec2/home#launchAmi=ami-0056ccb36f3fb6235

```
apk update && apk upgrade
reboot
```

The system will no longer boot.

tomalok in #alpine-cloud was able to locate the source of the issue:
(/boot/grub/grub.cfg is missing modules on line 99)

```
# diff /boot/grub/grub.cfg.backup /boot/grub/grub.cfg
--- /boot/grub/grub.cfg.backup
+++ /boot/grub/grub.cfg
@@ -72,9 +72,6 @@
   set gfxmode=auto
   load_video
   insmod gfxterm
-  set locale_dir=$prefix/locale
-  set lang=en_US
-  insmod gettext
 fi
 terminal_output gfxterm
 if [ x$feature_timeout_style = xy ] ; then
@@ -99,7 +96,7 @@
 	  search --no-floppy --fs-uuid --set=root a9a2c929-a544-4096-92bd-3c8d6d54ce18
 	fi
 	echo	'Loading Linux virt ...'
-	linux	/boot/vmlinuz-virt root=UUID=a9a2c929-a544-4096-92bd-3c8d6d54ce18 ro  modules=sd-mod,usb-storage,ext4,nvme,ena console=ttyS0,115200n8 nvme_core.io_timeout=4294967295
+	linux	/boot/vmlinuz-virt root=UUID=a9a2c929-a544-4096-92bd-3c8d6d54ce18 ro  modules=
 	echo	'Loading initial ramdisk ...'
 	initrd	/boot/initramfs-virt
 }
```

**Comment by tomalok** [comment]
The `/etc/default/grub` we install does not interpolate the string variables inside it -- but because those variables are `export`ed when we're setting things up, it works okay when we're creating the AMI.

solution is to use `envsubst` or some equivalent to make the `/etc/default/grub` contents static.
