### ISSUE TITLE
Could you please comment on how to use this repo?

### ISSUE THREAD

**Issue by helinwang** [mcrute/alpine-ec2-ami#17]
Hi,

Thank you for creating this repo! I am trying to use this repo to create a EBS volume size of 1GB alpine AWS AMI. However, I am not sure how to use this repo. Could you please comment some brief steps?

Currently I am confused about:

- Where to run `make_ami.sh`, is it on my local dev machine or an AWS instance?
- What are the prerequisites, e.g., is aws-cli required?

Thank you!

**Comment by mcrute** [comment]
Hi @helinwang. The easiest way to use this repo is to launch one of the AWS AMIs that are listed in the [README](https://github.com/mcrute/alpine-ec2-ami/blob/master/README.md). There's one in each commercial AWS region. You can use the [EC2 user-data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) shell scripts (but not cloud-init as it's not ported to Alpine yet). This is the easiest way to get up and running quickly.

If you want to build your own custom AMI then you'll need to use [Hashicorp Packer](https://www.packer.io/). Take a look at the [Makefile](https://github.com/mcrute/alpine-ec2-ami/blob/master/Makefile) steps for the actual details. The only requirements for building an AMI are a working installation of Packer, AWS credentials [exported in environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) and Python3. You will need to create a copy of [variables.yaml-default](https://github.com/mcrute/alpine-ec2-ami/blob/master/variables.yaml-default) and name it `variables.yaml`, which you can customize. then just run `make ami` to create the AMI in your AWS account. You do not need the AWS CLI.

I'd recommend the first approach for beginners and the second for power users. Let me know if you have any more specific questions after looking through the code.

**Comment by helinwang** [comment]
Hi @mcrute ,

Thank you!

I would love to launch the existing AMIs however the last time I checked it's 5GB but I needed 1GB.
It would be great if you could provide 1GB AMI too, since one big reason to use alpine is for the small size, and one can always scale up the disk size when launching the AMI, but he can not scale down.

I will try building manually according to your instructions.

**Comment by mcrute** [comment]
The `volume_size` setting in `variables.yaml` should do the trick for you. Aside from a YAML to JSON conversion that happens in the build step (because YAML supports comments and is generally easier to read for humans than JSON) everything else is standard packer with a shell script to do the on-host setup.

**Comment by mcrute** [comment]
@helinwang did that work for you? I'm going to close this issue but feel free to re-open it if needed.
