### ISSUE TITLE
Update tied to private s3 bucket

### ISSUE THREAD

**Issue by dominicholt** [mcrute/alpine-ec2-ami#2]
When running the "apk update" command as root, the following error displays:

ERROR: https://mcrute-build-artifacts.s3.us-west-2.amazonaws.com/alpine-packages/3.7/testing: Permission denied

My guess is that the update command references a private S3 bucket you created.

**Comment by mcrute** [comment]
Sorry about that. I rearranged the bucket and have an updated AMI that I’m testing for release next week. My repo is really only useful when bootstrapping the AMI, by the time you boot it everything that was needed is already installed. You can remove the repo from the repositories file to unblock your apk update. I’ll update this issue once I release the updated version next week.

**Comment by tejaashwine** [comment]
When running the make_ami.sh file tiny-ec2-bootstrap and ena package is missing as your s3 bucket permission has been revoked I guess. Kindly suggest me how to proceed with this issue.

**Comment by mcrute** [comment]
My apologies for the slow reply here. Thanks to the PR from @tomalok that should be fixed now. I'll build and release a new AMI this evening when I have some time to test it and report back.

**Comment by mcrute** [comment]
This change has been merged. There is no longer a dependency on a private S3 bucket.
