### ISSUE TITLE
Migrate AMIs to new AWS account

### ISSUE THREAD

**Issue by mcrute** [mcrute/alpine-ec2-ami#21]
The end goal of this repository is to contribute the AMIs to upstream Alpine and do releases on the same cadence as the official releases. To simplify accomplishing this we need a new AWS account that exists only to publish AMIs. @mcrute will pay for the storage and compute to build images on this account for now until there's a more clear path to upstream.

**Comment by tomalok** [comment]
I've got some cycles, and wouldn't mind setting up the new AWS account and sponsoring it for now.  We can always re-link under a different master account, or switch to a new one in the future.

**Comment by tomalok** [comment]
AMI's are all set in the new AWS account.  PR #38 will update the README, etc.

**Comment by tomalok** [comment]
AMIs are migrated!
