### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by mcrute** [mcrute/alpine-ec2-ami#22]
Setup CI so that images can be published immediately after release and so that we can handle rolling off old images. Possible options are Travis or Jenkins. I like Travis because it's free and fairly hands-off but an open to other opinions.

**Comment by tomalok** [comment]
I know there's a lot of everything still tied to GitHub, but what are your thoughts about GitLab and its integrated CI?

**Comment by mcrute** [comment]
Personally I'd prefer to stick with GitHub and use something like TravisCI to do the image building. I'm already using two different code hosting services and I'm not keen to add a third. Also, none of the Alpine developers seem to be using GitLab which would make it harder to push this all upstream when we get to that point.

**Comment by mcrute** [comment]
Well a lot has happened since this was opened. Now that GitHub actions are a think I thin we should use those. I think that we can use the [GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) feature of the build to allow the builder to authenticate with the identity broker and to do the builds and releases with each push to the profiles. I tried to lay the groundwork for that in the most recent tooling updates. What do you think @tomalok?

**Comment by tomalok** [comment]
Sounds good to me.

**Comment by oxr463** [comment]
> 
> 
> Personally I'd prefer to stick with GitHub and use something like TravisCI to do the image building. I'm already using two different code hosting services and I'm not keen to add a third. Also, none of the Alpine developers seem to be using GitLab which would make it harder to push this all upstream when we get to that point.

Perhaps this should be reconsidered since upstream now hosts their own GitLab instance.

**Comment by mcrute** [comment]
> Perhaps this should be reconsidered since upstream now hosts their own GitLab instance.

In general I'm supportive of using upstream infrastructure, however, there are a few moving pieces that need to be put in order to make that work well.

Probably the biggest issue is our identity broker, which allows access to our AWS accounts. Only people who do releases ever see this but it's essential to our release process. The broker exists to pivot an authenticated and authorized GitHub identity into an AWS identity and thereby eliminates the need for any long-lived AWS credentials. Sticking with GitHub for now allows us to use the `GITHUB_TOKEN` that is part of the CI environment, which makes using the broker much easier. Doing this in upstream's GitLab would require either implementing GitLab Oauth in the Identity broker, which is a good long-term plan; or provisioning and sharing a long-term secret that allows access to the broker, which is a deal-break as it significantly weakens our security posture.

The short-term plan is to get our release tooling updates finished and get new AMIs released, then to get all of that working in a fully-automated CI environment (probably GitHub). Longer-term we'll definitely be looking into GitLab Oauth in the broker and migrating to upstream CI, but making the process work with what we have first is higher priority.

You can follow #72 for more updates on the future upstream migration.

**Comment by mcrute** [comment]
Closing this in favor of #72
