### ISSUE TITLE
New AMIs not launching

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#24]
My newly built AMIs aren't launching -- they're not even getting as far as bootstrapping the kernel...  :(

Unfortunately, I was "clever" and removed my previous known-to-work AMIs, so I can't compare...  Shouldn't be anything in the latest PR #18 that would have caused this, AFAICT.

![example instance screenshot](https://user-images.githubusercontent.com/18317471/49346977-7116c600-f64e-11e8-9db3-d61b9ee84dd9.jpeg)

**Comment by tomalok** [comment]
There's a new Amazon Linux AMI built on 16 November that's being pulled in.  Explicitly specifying the previous one from 10 August in `alpine-ami.yaml` results in a bootable Alpine AMI.

Going to see if I can find any `extlinux` version or config changes between the two.

**Comment by IanS94** [comment]
Resolved this locally by adding the following to the start of make_filesystem()

    # Weird little tweak to mkfs so it doesn't make the filesystem 64Bit - that's actually a thing :'(
    # ExtLinux (Syslinux) doesn't work with 64 Bit Ext4.
    ex -s +'/ext4/+1 s/64bit,// | x' /etc/mke2fs.conf

Just above the mkfs.ext4 line :)
Would MR but seems you've found it anyway, your solution seems cleaner

**Comment by tomalok** [comment]
Just the boot volume needs to not have 64bit support -- better to leave it turned on by default for other potential volumes.

Closing, as the solution's been merged.
