### ISSUE TITLE
Can't build AMI

### ISSUE THREAD

**Issue by nelsongraca** [mcrute/alpine-ec2-ami#30]
I'm trying to build the AMI, but it seems like the package aws-ena-driver is missing.

```
ERROR: unsatisfiable constraints:
   aws-ena-driver (missing):
     required by: world[aws-ena-driver]
```

**Comment by IanS94** [comment]
It's no longer a package in the edge or 3.8 repos. Not sure if that's as it's in the core OS now, as the 3.8.2 changelog does refer to it

**Comment by nelsongraca** [comment]
From what I understand after checking the changelog it should be available in the testing repos, but my knowledge on that is quite limited.

**Comment by tomalok** [comment]
the aws-ena-driver that was being used was from edge.  however, the linux-virt (well, and -vanilla) package has the AWS driver in it already.  It's been enabled as a module there, and apparently the old edge package has been removed.

i should be able to provide a PR in short order to fix things.

**Comment by nelsongraca** [comment]
@tomalok so simply removing the package should work? I will be waiting on the PR also.

**Comment by tomalok** [comment]
@nelsongraca I'll be testing that theory shortly.

**Comment by nelsongraca** [comment]
@tomalok I went ahead and tried it, the AMI was built and the module is there.
`
$  modinfo ena
filename:       /lib/modules/4.19.14-0-virt/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        1.5.0K
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     0646520359090667B5A1C01
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:        
intree:         Y
name:           ena
vermagic:       4.19.14-0-virt SMP mod_unload modversions 
parm:           debug:Debug level (0=none,...,16=all) (int)
`

**Comment by tomalok** [comment]
@nelsongraca the module should be there, because i submitted the patch to put it there...  :)

I also removed the edge repo dependency for the `linux-virt` package.

PR #31

**Comment by tomalok** [comment]
@nelsongraca all pending PRs have been merged (thanks, @mcrute), so you should be able to build 3.8.2 without adjustments.

Also note, alpine 3.9 is getting close, rc's started showing up recently.
