### ISSUE TITLE
nvme-ebs-links sometimes "comes up short"

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#40]
I've now seen a couple times where the `nvme-ebs-links` mdev script does a `nvme id-ctrl ...` to read the EBS volume name, but only gets part of the EBS volume name (i.e. 'x' instead of 'xvdb') -- almost as if whatever manages that value hadn't quite written it all there yet.

Seems to be most prevalent after partitioning a volume...

**Comment by oliwer** [comment]
Other distributions like CoreOS use `nvme id-ctrl --raw-binary "$1" | cut -c3073-3104` instead of `dd bs=32 skip=96 count=1`. I wonder if that could make a difference.

To be safe, we could change the test from `[ -n "$EBS" ]` to `[ ${#EBS} -gt 3 ]`.

**Comment by tomalok** [comment]
That's where I originally started.  For whatever reason (likely the `busybox` implementation), `cut` was simply not working properly on Alpine.  I could see what I wanted to grab (at 0xc00 - 0xc1f) by piping through `hd`, and `dd` works properly with binary data.

Safer check...
* don't strip off the trailing spaces right away
* ensure `$EBS =~ /(xv|s)d[a-z]{1,2} /`, otherwise try again
  * usually we can expect one device id character, although I've seen reference to possibly two.
* strip off extraneous spaces

**Comment by tomalok** [comment]
The "3.9.0-1" AMIs should take care of this issue -- I've been using AMIs with this fix for about a week now, with no problems.

**Comment by sedlund** [comment]
Having problems with /lib/mbed/nvme-ebs-links eating 100% cpu on a t3.nano with 3.9.1 (ami-054428bd9a4f1da32) after attaching another ebs volume.

It will also not boot if the volume is attached, hanging at busybox: mdev
