### ISSUE TITLE
nvme-ebs-links eating 100% cpu

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#44]
@tomalok 
Having problems with /lib/mbed/nvme-ebs-links eating 100% cpu on a t3.nano with 3.9.1 (ami-054428bd9a4f1da32) after attaching another ebs volume.

It will also not boot if the volume is attached, hanging at busybox: mdev

_Originally posted by @sedlund in https://github.com/mcrute/alpine-ec2-ami/issues/40#issuecomment-469058817_

**Comment by tomalok** [comment]
Will investigate a little later today.

**Comment by tomalok** [comment]
it appears that sometimes EC2 will sometimes say the EBS device is `sdX`, sometimes it's `xvdX`, and (here's what was missed) sometimes it's `/dev/sdX`(and presumably `/dev/xvdX` may also be valid.

I'll update the regex to allow for the possibility of a leading `/dev/`, maybe add a small sleep to the loop, and timeout with a syslog error after a certain number of tries.

**Comment by tomalok** [comment]
@sedlund - Please try the updated `/lib/mdev/nvme-ebs-links` script from PR #45 -- that should do the trick for you.

**Comment by sedlund** [comment]
Tested hot add ebs volume, added to fstab and reboot with auto-mount. Works now.

Thank you!

**Comment by tomalok** [comment]
Thanks for verifying, I'll roll a fresh set of `alpine-ami-3.9.1-1-x86_64` AMIs tomorrow.

**Comment by tomalok** [comment]
Fresh set of `alpine-ami-3.9.2.x86_64` AMIs have been rolled.
