### ISSUE TITLE
Addition to README - helpful info about tiny-ec2-bootstrap?

### ISSUE THREAD

**Issue by phlummox** [mcrute/alpine-ec2-ami#48]
I ran into an issue trying to make a new AMI based on the ones provided here (for which, thank you, they are much appreciated!) - I was completely unable to ssh into instances created from the AMI, regardless of what I did.

I eventually discovered the issue was spelled out in the `tiny-ec2-bootstrap` README: if the tool you use to make a new AMI ([`packer`](https://www.packer.io/), in my case) doesn't delete `/var/lib/cloud/.bootstrap-complete`, then an instance created from the AMI will ignore all attempts at setting a login key...

I wondered if it might be worth mentioning this in the README, since a lot of Amazon's documentation is geared towards AMIs that use `cloud-init`, so tracking down the issue took a long time.

Thanks again!

**Comment by tomalok** [comment]
Thanks @phlummox, I'll add a note the "caveats" section of the README in the near future.

**Comment by phlummox** [comment]
Many thanks!
