### ISSUE TITLE
How to create custom image?

### ISSUE THREAD

**Issue by shatgupt** [mcrute/alpine-ec2-ami#5]
Sorry for this naive question but I couldn't figure out how to modify some parameters and generate my own image.

I just want to run a python script and hence I want to make an image as small as possible, which can be 1GB per EBS limits.

I figured out there are `volume_size` configs for input instance and ami_root in `alpine-ami.yaml` which I can reduce to 1GB. Am I correct? If yes, then do I have to run simply `make` or the `make_ami.sh` script?

Also, what are the pre-requisites apart from packer and make?

PS: Is there a reason you chose 5GB as volume size? I think Alpine would easily fit in 1GB.

**Comment by shatgupt** [comment]
The actual disk usage of freshly launched instance is around 540M and with python and python3 installed it is 640M. I think you can reduce the size to 1GB and have python installed by default since I feel it is a quite useful addition and anyways won't affect final disk size which still going to be 1GB.

Also simple `sudo add python` didn't work. I had to add `--no-cache`.
```sh
ip-172-31-0-51:~$ sudo apk add python
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.4dabf18d.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
ip-172-31-0-51:~$ sudo apk add  --no-cache python
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
fetch https://mcrute-build-artifacts.s3.us-west-2.amazonaws.com/alpine-packages/3.7/testing/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://mcrute-build-artifacts.s3.us-west-2.amazonaws.com/alpine-packages/3.7/testing/x86_64/APKINDEX.tar.gz: Permission denied
(1/10) Installing libbz2 (1.0.6-r6)
(2/10) Installing expat (2.2.5-r0)
(3/10) Installing libffi (3.2.1-r4)
(4/10) Installing gdbm (1.13-r1)
(5/10) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(6/10) Installing ncurses-terminfo (6.0_p20171125-r0)
(7/10) Installing ncurses-libs (6.0_p20171125-r0)
(8/10) Installing readline (7.0.003-r0)
(9/10) Installing sqlite-libs (3.21.0-r0)
(10/10) Installing python2 (2.7.14-r2)
Executing busybox-1.27.2-r7.trigger
OK: 565 MiB in 56 packages
```

**Comment by jaybauson** [comment]
Following... I am still puzzled on how we can use this to build our own images.

**Comment by mcrute** [comment]
The minimum volume size for EBS is 1GB so you won't be able to shrink the volume size below that. PR #6 does decrease the default volume size. I chose 5GB because I estimated that this would be about the right size for most small projects that didn't want to mount a second EBS volume.

The only other prerequisites other than packer and make are an AWS account that you can launch instances into.

Make sure you run `apk update` first if you want to avoid the no-cache. I don't cache APK updates in the image because they'd be perpetually out of date.

Although if you want to make your own image I'd recommend that you just use my AMI as a base for your own packer build.  The current AMI IDs are in the repo README and I push new builds every time the code is updated, which has been admittedly somewhat slow lately.

**Comment by tomalok** [comment]
I'm working on another PR that will add the ability to configure a lot more via `variables.json`.

**Comment by tomalok** [comment]
Just submitted PR #7 which should come in handy for those wanting to build their own AMIs.

**Comment by tomalok** [comment]
I've also submitted some PRs to alpinelinux/aports for things that help us here...

https://github.com/alpinelinux/aports/pull/5023 - updating the AWS ENA driver to 1.5.3
https://github.com/alpinelinux/aports/pull/5024 - build NVMe modules for x86* linux virt flavor
https://github.com/alpinelinux/aports/pull/5025 - add e2fstools-extra dependency for tiny-ec2-bootstrap

**Comment by tomalok** [comment]
The pending alpinelinux/aports changes have landed in edge.  Submitted PR #13 to incorporate them.

Also relevant to this thread, v1.2.0 of the `tiny-ec2-bootstrap` package will also resize a newly launched instance's root volume, if it's specified to be larger than the 1 GiB AMI image.

**Comment by mcrute** [comment]
I think all the blockers for this issue have been resolved. I'm going to close it but if there are any remaining issues feel free to re-open.
