### ISSUE TITLE
Move alpine user home to not conflict with NFS/EFS /home mounts

### ISSUE THREAD

**Issue by tsarna** [mcrute/alpine-ec2-ami#59]
Enhancement request:

/home is so commonly used for NFS mounted home directories (including EFS on EC2), that having the alpine user's home there is problematic. It's a hassle to deal with moving it using eg ansible or creating a derivative packer image since it's typically the ansible user itself that would be used to do that, and these tools don't particularly like having $HOME disappear out from under them.

I'd like to request that the default be changed to something like /alpine (a'la /root), or some other location that is unlikely to conflict with a commonly used mount point.

**Comment by mcrute** [comment]
The approach in the Alpine image mirrors that of other AMIs (Ubuntu, Amazon Linux, Fedora, etc...) so I'm reticent to change that and risk breaking common assumptions for users.

There are at least two other possible ways to handle this case. One would be to make the home directory swap using a shell script in the instance user-data. Presumably you're already using this to bootstrap Ansible on the host; if so this can be done in your existing bootstrap script.

Another option that would require updates to the image would be to allow key-only SSH access as root and update the bootstrapper to also write SSH keys for root. Then it would be possible to bootstrap the image as root and totally ignore or remove the alpine user.

Do either of these work for your use-case?

**Comment by tsarna** [comment]
I was trying to avoid using instance user-data, but I have switched to this approach. Thanks for responding, and thanks or your work on these images!
