### ISSUE TITLE
unable to log into ec2 instance after creation

### ISSUE THREAD

**Issue by junkb** [mcrute/alpine-ec2-ami#64]
hi-

i've created a couple of different ec2 instances from the following amis:

* alpine-ami-edge-x86_64-20200403021415 [ami-034b4fb0ea71693e3]
* alpine-ami-3.11.5-x86_64-r0 [ami-02fa6ea44ed68cbd1]

the creation of the ec2 instance appears to go well, but i'm unable to ssh:

>ssh -vi ~/.ssh/keys/aws-ec2_default-id_rsa alpine@xx.xx.xx.xx
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/localadmin/.ssh/config
debug1: /Users/localadmin/.ssh/config line 226: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 22.
debug1: Connection established.
debug1: identity file /Users/localadmin/.ssh/keys/aws-ec2_default-id_rsa type 0
debug1: identity file /Users/localadmin/.ssh/keys/aws-ec2_default-id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2
debug1: match: OpenSSH_8.2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to xx.xx.xx.xx:22 as 'alpine'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:FdZdi0GCPUcFG6beSQeWtoxXt2cflQRKjizOWp4ZkQs
debug1: Host 'xx.xx.xx.xx' is known and matches the ED25519 host key.
debug1: Found key in /Users/localadmin/.ssh/known_hosts:530
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key:  RSA SHA256:nVH/fq39jd8EtRgsHapJSkmfHYBt9kF1Ld6b3+9k9bI agent
debug1: Will attempt key: /Users/localadmin/.ssh/keys/aws-ec2_default-id_rsa RSA SHA256:WQWW4Tg8klA49FkqeijWamj3ZzsxBhyarTWLnp+0Wkc explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key:  RSA SHA256:nVH/fq39jd8EtRgsHapJSkmfHYBt9kF1Ld6b3+9k9bI agent
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Offering public key: /Users/localadmin/.ssh/keys/aws-ec2_default-id_rsa RSA SHA256:WQWW4Tg8klA49FkqeijWamj3ZzsxBhyarTWLnp+0Wkc explicit
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
alpine@xx.xx.xx.xx's password:

it appears to be attempting to use the key, but the remote side is not accepting it.

connecting to ec2 instances created from other amis [for example amazone linux] seem to work as expected.

how can i troubleshoot what i'm doing wrong?

thanks

**Comment by junkb** [comment]
after experimenting a bit more, it seems like the instance metadata retrieval isn't working as expected.

i attached the volume to another instance and inspected, and ~alpine/.ssh/authorized_keys is present, but empty.  i manually populated it and was then able to log in as alpine.  at that point i also noticed that the system hostname was not set.

if i'm understanding the initialization mechanism correctly, tiny-ec2-bootstrap is what does all of this.  if i emulate it, for example, to get the system's hostname, i get this:

>curl -v 'http://169.254.169.254/latest/meta-data/hostname'
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/hostname HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 401 Unauthorized
< Content-Length: 343
< Content-Type: text/html
< Date: Tue, 14 Apr 2020 01:05:39 GMT
< Connection: close
< Server: EC2ws
<
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>
* Closing connection 0

i'm new to aws, so i don't know what's normal and what's not, or what i may have inadvertently configured to be atypical, but it appears that a token must be retrieved first - e.g.:

>token=$(curl -X PUT 'http://169.254.169.254/latest/api/token' -H 'X-aws-ec2-metadata-token-ttl-seconds: 21600') \
> && curl -H "X-aws-ec2-metadata-token: ${token}" -v 'http://169.254.169.254/latest/meta-data/hostname'; echo ''
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0  11200      0 --:--:-- --:--:-- --:--:-- 11200
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/hostname HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.69.1
> Accept: */*
> X-aws-ec2-metadata-token: AQAAAONM5s-Hv_n77Hs4TLJrTq1_C95RAybrg1Jyxej72PDQe0H0HQ==
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Accept-Ranges: bytes
< Content-Length: 30
< Content-Type: text/plain
< Date: Tue, 14 Apr 2020 01:08:10 GMT
< Last-Modified: Tue, 14 Apr 2020 00:33:56 GMT
< X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
< Connection: close
< Server: EC2ws
<
* Closing connection 0
ip-nn-nn-nn-nn.example.com

from what i can tell, tiny-ec2-bootstrap isn't doing this.

**Comment by junkb** [comment]
i think i've figured this out.  i'd been creating ec2 instances that required version 2 of the instance metadata service:

https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/configuring-instance-metadata-service.html

this requires a token, whereas version 1 of the service does not.  i created a new instance allowing version 1, and everything works fine.

would a feature request for support of version 2 be considered?

**Comment by tomalok** [comment]
I think this issue / feature request would be best addressed over at https://github.com/mcrute/tiny-ec2-bootstrap

**Comment by mcrute** [comment]
@junkb: I agree with @tomalok that mcrute/tiny-ec2-bootstrap is the correct place for this issue. I've opened mcrute/tiny-ec2-bootstrap#6 to address this. I'll try to get to it next week but would also be open to accepting pull requests if you'd like to take a crack at it.

**Comment by junkb** [comment]
sounds good to me, thanks

**Comment by mcrute** [comment]
The IMDSv2 changes for tiny-ec2-bootstrap were merged to Alpine Edge this morning (PST) and should be available if you're using edge.

**Comment by tomalok** [comment]
I should be able to build a new edge AMI in the near future.
