### ISSUE TITLE
Become an "Official" Alpine project

### ISSUE THREAD

**Issue by tsarna** [mcrute/alpine-ec2-ami#74]
Tying together some ideas related to a couple of other issues, such as using Alpine's gitlab:

I'm not sure what it would take to get the project officially blessed by Alpine and be able to state on https://github.com/mcrute/alpine-ec2-ami/blob/master/releases/README.md that these ARE official Alpine images, but I'm happy to help lobby for it in any way I can.

I think anything that can be done to look more official would be great for adoption. No offense intended, but people are more likely to trust an Alpine OS image that "comes from Alpine" and not just "some guy called Mike" :wink:

Getting links from https://www.alpinelinux.org/downloads/ to the AMIs would also be huge.

Finally, I wonder if this became an official Alpine project if you could get them to accept contributions and deal with all the administrative and transparency stuff and paying the AWS bill?

And once again, thanks so much for all your work!

**Comment by mcrute** [comment]
I completely agree with you. My plan has been to get the release tools updated, the 3.12 images out, and then make the case to pull this into upstream officially. I need to start the conversation with Natanael at some point, and my point for that is once the 3.12 images are released. If you're in a position within upstream to help move that forward I'd very much appreciate your support, please get in touch off GitHub (mike[at]crute[dot]us). Thanks!

**Comment by tsarna** [comment]
I have no special influence at all, but I'm happy to provide testimonials, emails of support, thumbs-up on gitlab issues, or whatever else I can do as a lowly user to try to push it forward!

**Comment by mcrute** [comment]
Thanks! I've reached out to Natanael and will update this issue once I know more.

**Comment by mcrute** [comment]
This conversation is ongoing with upstream and is currently blocked pending the 3.13 release. I'll update again once there's information to share.

**Comment by mcrute** [comment]
The cloud images are now official. See the [Alpine Cloud Page](https://alpinelinux.org/cloud/) for more details. We're going to continue working on GitHub for now but are looking into migrating our infrastructure to Alpine GitLab in the future.
