### ISSUE TITLE
eth-eni-hotplug prevents the use of non-eth interfaces like bridges, wireguard, etc.

### ISSUE THREAD

**Issue by tsarna** [mcrute/alpine-ec2-ami#91]
eth-eni-hotplug prevents the use of non-eth interfaces like bridges, wireguard, etc, since it overwrites /etc/network/interfaces  using only `lo` and any enumerated `eth` interfaces. Even if a file is present in interfaces.d, for example `wg0` or `docker0`, it will not be included.

**Comment by tomalok** [comment]
The intent was for any additional interfaces to be defined in `/etc/network/interfaces.d/` for assembly into the primary `/etc/network/interfaces`...  But additional interfaces were not tested.

Could you provide a simple additional interface config that could be used for testing?

**Comment by tsarna** [comment]
I guess the simplest example is a bridge. One of my use cases is to preconfigure a bridge for docker to ensure it has a fixed address and so that unbound can bind to the interface before docker is up.

You'll need to `apk add bridge` for this.

/etc/network/interfaces.d/docker0:

```
# Pre-create docker0 to fix its address for the DNS resolver
auto docker0
iface docker0 inet static
  bridge-ports none
  bridge-stp 0
  address 172.17.0.1
  netmask 255.255.0.0
```

**Comment by tsarna** [comment]
I guess eth-eni-setup also generates the interfaces file, so it would need fixing in both places, or for the code to be factored out into some common location
