### ISSUE TITLE
update releases/<profile>.yaml based on what's really there

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#96]
Perhaps the new `release` subcommand could also traverse the regions and update `releases/<profile>.yaml` with the matching AMIs that actually exist there.

Or, the same broker mechanism used in `release` could be used in a different subcommand.

No/few changes to the code to update `releases/README.md` should be necessary as long as the release's YAML is fully fleshed out.

**Comment by mcrute** [comment]
I really like this idea. I'd like to see `release/<profile>.yaml` be nothing but a generated artifact based on all the tags of the images in all regions. Currently there is some data in the YAML file that's not tagged to images in various regions that would need to be backfilled. I did a bunch of analysis a few months ago (and misplaced all that work, argh!) about what would need to be backfilled to where. There are also some images in regions that are not in the YAML which will need reconciled (probably deleted).

I'd eventually like to just generate a YAML, JSON, and HTML file for the current state of the world and publish it into an S3 bucket similar to the old Ubuntu cloud image finder. If we really wanted to get clever we could hook the JSON and YAML files up to an SNS notification that downstream users could subscribe to for update notifications.
